
import type { UsuarioFirebase } from '@/lib/types';

export const mockUsuarios: UsuarioFirebase[] = [
  // --- Empresa 1: Construcciones Modernas S.L. ---
  {
    id: 'user-1-admin',
    empresaId: 'empresa-1',
    nombre: 'Admin CM (Empresa Demo)',
    email: 'empresa@example.com',
    dni: 'A00000000', 
    password: 'empresa', 
    rol: 'admin',
    activo: true,
    obrasAsignadas: ['obra-1-1', 'obra-1-2', 'obra-1-3', 'obra-1-4', 'obra-1-5', 'obra-1-6'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-jefeobra-1', // Carlos López
    empresaId: 'empresa-1',
    nombre: 'Carlos López (Jefe Obra CM)',
    email: 'jefeobra.cm@example.com',
    dni: 'B11111111', 
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-1-1', 'obra-1-3', 'obra-1-5'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-jefeobra-2', // Elena García
    empresaId: 'empresa-1',
    nombre: 'Elena García (Jefa Obra CM)',
    email: 'elena.garcia.jo@example.com',
    dni: 'B22222222', 
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-1-2', 'obra-1-4', 'obra-1-6'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Elena+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Elena+R',
  },
  {
    id: 'user-1-jefeobra-3', // Nuevo Jefe de Obra para Empresa 1
    empresaId: 'empresa-1',
    nombre: 'Roberto Sanz (Jefe Obra CM)',
    email: 'roberto.sanz.jo@example.com',
    dni: 'B33333333',
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-1-5', 'obra-1-6'], // Asignado a nuevas obras
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-trabajador-1', // Lucía Fernández
    empresaId: 'empresa-1',
    nombre: 'Lucía Fernández (Trabajadora Demo)',
    email: 'trabajador@example.com',
    dni: '12345678A', 
    password: 'trabajador',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-1', 'obra-1-3', 'obra-1-5'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Lucia+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Lucia+R',
  },
  {
    id: 'user-1-trabajador-2', // Marcos García
    empresaId: 'empresa-1',
    nombre: 'Marcos García (Trabajador CM)',
    email: 'marcos.g@example.com',
    dni: '87654321B', 
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-2', 'obra-1-4', 'obra-1-6'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-trabajador-3', // Javier Soler
    empresaId: 'empresa-1',
    nombre: 'Javier Soler (Trabajador CM)',
    email: 'javier.s@example.com',
    dni: '11122233C',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-1', 'obra-1-2', 'obra-1-4', 'obra-1-5'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-trabajador-4', // Sofía Navarro
    empresaId: 'empresa-1',
    nombre: 'Sofía Navarro (Trabajadora CM)',
    email: 'sofia.n@example.com',
    dni: '22233344D',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-3', 'obra-1-4', 'obra-1-6'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Sofia+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Sofia+R',
  },
  {
    id: 'user-1-trabajador-5', // David Reyes
    empresaId: 'empresa-1',
    nombre: 'David Reyes (Trabajador CM)',
    email: 'david.r@example.com',
    dni: '33344455E',
    password: 'password123',
    rol: 'trabajador',
    activo: false, 
    obrasAsignadas: ['obra-1-1', 'obra-1-5'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-trabajador-6', // Nuevo Trabajador para Empresa 1
    empresaId: 'empresa-1',
    nombre: 'Andrea Gil (Trabajadora CM)',
    email: 'andrea.gil@example.com',
    dni: '44455566F',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-2', 'obra-1-5', 'obra-1-6'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-trabajador-7', // Nuevo Trabajador para Empresa 1
    empresaId: 'empresa-1',
    nombre: 'Sergio Peña (Trabajador CM)',
    email: 'sergio.pena@example.com',
    dni: '55566677G',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-1', 'obra-1-3', 'obra-1-6'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Sergio+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Sergio+R',
  },

  // --- Empresa 2: Reformas Integrales Alfa ---
  {
    id: 'user-2-admin',
    empresaId: 'empresa-2',
    nombre: 'Sofía Ramírez (Admin Alfa)',
    email: 'admin.alfa@example.com',
    dni: 'C22222222', 
    password: 'password123',
    rol: 'admin',
    activo: true,
    obrasAsignadas: ['obra-2-1', 'obra-2-2', 'obra-2-3'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-2-jefeobra-1', // Ricardo Montes
    empresaId: 'empresa-2',
    nombre: 'Ricardo Montes (Jefe Obra Alfa)',
    email: 'ricardo.montes.jo@example.com',
    dni: 'D44444444',
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-2-1', 'obra-2-2'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-2-jefeobra-2', // Nuevo Jefe de Obra para Empresa 2
    empresaId: 'empresa-2',
    nombre: 'Mónica Vidal (Jefa Obra Alfa)',
    email: 'monica.vidal.jo@example.com',
    dni: 'D55555555',
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-2-3'], // Asignada a nueva obra
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Monica+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Monica+R',
  },
  {
    id: 'user-2-trabajador-1', // David Sanz
    empresaId: 'empresa-2',
    nombre: 'David Sanz (Trabajador Alfa)',
    email: 'david.s@example.com',
    dni: '11223344C', 
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-2-1', 'obra-2-3'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-2-trabajador-2', // Ana Torres
    empresaId: 'empresa-2',
    nombre: 'Ana Torres (Trabajadora Alfa)',
    email: 'ana.t@example.com',
    dni: '55667788D',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-2-1', 'obra-2-2'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Ana+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Ana+R',
  },
  {
    id: 'user-2-trabajador-3', // Nuevo Trabajador para Empresa 2
    empresaId: 'empresa-2',
    nombre: 'Carlos Ruiz (Trabajador Alfa)',
    email: 'carlos.ruiz@example.com',
    dni: '66778899E',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-2-2', 'obra-2-3'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-2-trabajador-4', // Nuevo Trabajador para Empresa 2
    empresaId: 'empresa-2',
    nombre: 'Laura Gómez (Trabajadora Alfa)',
    email: 'laura.gomez@example.com',
    dni: '77889900F',
    password: 'password123',
    rol: 'trabajador',
    activo: false, // Inactivo
    obrasAsignadas: ['obra-2-1'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },

  // --- Empresa 3: Edifica Futuro Group ---
   {
    id: 'user-3-admin',
    empresaId: 'empresa-3',
    nombre: 'Elena Vazquez (Admin Edifica)',
    email: 'admin.edifica@example.com',
    dni: 'E33333333', 
    password: 'password123',
    rol: 'admin',
    activo: true,
    obrasAsignadas: ['obra-3-1', 'obra-3-2', 'obra-3-3', 'obra-3-4'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-3-jefeobra-1', // Miguel Torres
    empresaId: 'empresa-3',
    nombre: 'Miguel Torres (Jefe Obra Edifica)',
    email: 'jefeobra.edifica@example.com',
    dni: 'F44444444', 
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-3-1', 'obra-3-3'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
   {
    id: 'user-3-jefeobra-2', // Laura Campos
    empresaId: 'empresa-3',
    nombre: 'Laura Campos (Jefa Obra Edifica)',
    email: 'laura.campos.jo@example.com',
    dni: 'F55555555', 
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-3-2', 'obra-3-4'], // Asignada a nueva obra
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-3-jefeobra-3', // Nuevo Jefe de Obra para Empresa 3
    empresaId: 'empresa-3',
    nombre: 'Javier Martín (Jefe Obra Edifica)',
    email: 'javier.martin.jo@example.com',
    dni: 'F66666666',
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-3-4'], // Asignado a nueva obra
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-3-trabajador-1', // Laura Jimenez
    empresaId: 'empresa-3',
    nombre: 'Laura Jimenez (Trabajadora Edifica)',
    email: 'laura.j@example.com',
    dni: '55667788E', 
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-3-1', 'obra-3-2', 'obra-3-4'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-3-trabajador-2', // Pedro Ramos
    empresaId: 'empresa-3',
    nombre: 'Pedro Ramos (Trabajador Edifica)',
    email: 'pedro.r@example.com',
    dni: '99887766F',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-3-1', 'obra-3-3'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Pedro+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Pedro+R',
  },
  {
    id: 'user-3-trabajador-3', // Nuevo Trabajador para Empresa 3
    empresaId: 'empresa-3',
    nombre: 'Isabel Roca (Trabajadora Edifica)',
    email: 'isabel.roca@example.com',
    dni: '88776655G',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-3-2', 'obra-3-3', 'obra-3-4'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-3-trabajador-4', // Nuevo Trabajador para Empresa 3
    empresaId: 'empresa-3',
    nombre: 'Mario Luna (Trabajador Edifica)',
    email: 'mario.luna@example.com',
    dni: '77665544H',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-3-1'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Mario+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Mario+R',
  },
];
