
import type { UsuarioFirebase } from '@/lib/types';

export const mockUsuarios: UsuarioFirebase[] = [
  // --- Empresa 1: Construcciones Modernas S.L. ---
  {
    id: 'user-1-admin',
    empresaId: 'empresa-1',
    nombre: 'Admin CM (Empresa Demo)',
    email: 'empresa@example.com',
    dni: 'A00000000', 
    password: 'empresa', 
    rol: 'admin',
    activo: true,
    obrasAsignadas: ['obra-1-1', 'obra-1-2', 'obra-1-3', 'obra-1-4'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-jefeobra-1', // Carlos López
    empresaId: 'empresa-1',
    nombre: 'Carlos López (Jefe Obra CM)',
    email: 'jefeobra.cm@example.com',
    dni: 'B11111111', 
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-1-1', 'obra-1-3'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-jefeobra-2', // Elena García
    empresaId: 'empresa-1',
    nombre: 'Elena García (Jefa Obra CM)',
    email: 'elena.garcia.jo@example.com',
    dni: 'B22222222', 
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-1-2', 'obra-1-4'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Elena+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Elena+R',
  },
  {
    id: 'user-1-trabajador-1', // Lucía Fernández
    empresaId: 'empresa-1',
    nombre: 'Lucía Fernández (Trabajadora Demo)',
    email: 'trabajador@example.com',
    dni: '12345678A', 
    password: 'trabajador',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-1', 'obra-1-3'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Lucia+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Lucia+R',
  },
  {
    id: 'user-1-trabajador-2', // Marcos García
    empresaId: 'empresa-1',
    nombre: 'Marcos García (Trabajador CM)',
    email: 'marcos.g@example.com',
    dni: '87654321B', 
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-2', 'obra-1-4'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-trabajador-3', // Javier Soler
    empresaId: 'empresa-1',
    nombre: 'Javier Soler (Trabajador CM)',
    email: 'javier.s@example.com',
    dni: '11122233C',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-1', 'obra-1-2', 'obra-1-4'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-1-trabajador-4', // Nuevo trabajador
    empresaId: 'empresa-1',
    nombre: 'Sofía Navarro (Trabajadora CM)',
    email: 'sofia.n@example.com',
    dni: '22233344D',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-1-3', 'obra-1-4'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Sofia+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Sofia+R',
  },
  {
    id: 'user-1-trabajador-5', // Otro nuevo trabajador
    empresaId: 'empresa-1',
    nombre: 'David Reyes (Trabajador CM)',
    email: 'david.r@example.com',
    dni: '33344455E',
    password: 'password123',
    rol: 'trabajador',
    activo: false, // Para tener un trabajador inactivo de ejemplo
    obrasAsignadas: ['obra-1-1'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },

  // --- Empresa 2: Reformas Integrales Alfa ---
  {
    id: 'user-2-admin',
    empresaId: 'empresa-2',
    nombre: 'Sofía Ramírez (Admin Alfa)',
    email: 'admin.alfa@example.com',
    dni: 'C22222222', 
    password: 'password123',
    rol: 'admin',
    activo: true,
    obrasAsignadas: ['obra-2-1', 'obra-2-2'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-2-jefeobra-1', // Ricardo Montes
    empresaId: 'empresa-2',
    nombre: 'Ricardo Montes (Jefe Obra Alfa)',
    email: 'ricardo.montes.jo@example.com',
    dni: 'D44444444',
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-2-1', 'obra-2-2'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-2-trabajador-1', // David Sanz
    empresaId: 'empresa-2',
    nombre: 'David Sanz (Trabajador Alfa)',
    email: 'david.s@example.com',
    dni: '11223344C', 
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-2-1'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-2-trabajador-2', // Ana Torres
    empresaId: 'empresa-2',
    nombre: 'Ana Torres (Trabajadora Alfa)',
    email: 'ana.t@example.com',
    dni: '55667788D',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-2-1', 'obra-2-2'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Ana+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Ana+R',
  },

  // --- Empresa 3: Edifica Futuro Group ---
   {
    id: 'user-3-admin',
    empresaId: 'empresa-3',
    nombre: 'Elena Vazquez (Admin Edifica)',
    email: 'admin.edifica@example.com',
    dni: 'E33333333', 
    password: 'password123',
    rol: 'admin',
    activo: true,
    obrasAsignadas: ['obra-3-1', 'obra-3-2', 'obra-3-3'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-3-jefeobra-1', // Miguel Torres
    empresaId: 'empresa-3',
    nombre: 'Miguel Torres (Jefe Obra Edifica)',
    email: 'jefeobra.edifica@example.com',
    dni: 'F44444444', 
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-3-1', 'obra-3-3'], 
    dniAnversoURL: null,
    dniReversoURL: null,
  },
   {
    id: 'user-3-jefeobra-2', // Laura Campos
    empresaId: 'empresa-3',
    nombre: 'Laura Campos (Jefa Obra Edifica)',
    email: 'laura.campos.jo@example.com',
    dni: 'F55555555', 
    password: 'password123',
    rol: 'jefeObra',
    activo: true,
    obrasAsignadas: ['obra-3-2'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-3-trabajador-1', // Laura Jimenez
    empresaId: 'empresa-3',
    nombre: 'Laura Jimenez (Trabajadora Edifica)',
    email: 'laura.j@example.com',
    dni: '55667788E', 
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-3-1', 'obra-3-2'],
    dniAnversoURL: null,
    dniReversoURL: null,
  },
  {
    id: 'user-3-trabajador-2', // Pedro Ramos
    empresaId: 'empresa-3',
    nombre: 'Pedro Ramos (Trabajador Edifica)',
    email: 'pedro.r@example.com',
    dni: '99887766F',
    password: 'password123',
    rol: 'trabajador',
    activo: true,
    obrasAsignadas: ['obra-3-1', 'obra-3-3'],
    dniAnversoURL: 'https://placehold.co/300x200.png?text=DNI+Pedro+A',
    dniReversoURL: 'https://placehold.co/300x200.png?text=DNI+Pedro+R',
  },
];
